import type { Source } from "./schema";

export const sources = [
  { id: "gree-e6-guide", title: "GREE Mini Split E6 Error Code Troubleshooting", publisher: "Gree Comfort", url: "https://www.greecomfort.com/news-and-events/gree-mini-split-e6-error-code-troubleshooting-guide/index.html", sourceType: "oem-support", scopeNote: "Residential Gree single-zone and multi-zone communication diagnostics." },
  { id: "gree-multi21-service", title: "Multi21+ Service Manual", publisher: "Gree Comfort", url: "https://www.greecomfort.com/assets/documents/archive/multi21-revision-b/service-manual-30k-36k-42k.pdf", sourceType: "oem-service-manual", scopeNote: "Multi21+ 30K, 36K, and 42K equipment documented in the manual." },
  { id: "gree-h5-guide", title: "GREE H5 Error Code: IPM Protection Causes and Fix Guide", publisher: "Gree Comfort", url: "https://www.greecomfort.com/news-and-events/gree-h5-error-code-ipm-protection-guide/", sourceType: "oem-support", scopeNote: "Gree residential systems covered by the manufacturer technical article." },
  { id: "gree-water-leak", title: "Why Is My Mini-Split Leaking Water?", publisher: "Gree Comfort", url: "https://www.greecomfort.com/news-and-events/mini-split-leaking-water/", sourceType: "oem-support", scopeNote: "General ductless condensate and drainage guidance from Gree." },
  { id: "daikin-u4-service", title: "RZR-P and RZQ-P(9) Series Service Manual", publisher: "Daikin Comfort Technologies", url: "https://www.daikinac.com/content/assets/DOC/ServiceManuals/SiUS281117%20RZR-P%2CRZQ-P%289%29%20SkyAir%20Service%20Manual.pdf", sourceType: "oem-service-manual", scopeNote: "SkyAir RZR-P and RZQ-P(9) series equipment listed by Daikin." },
  { id: "daikin-a5-service", title: "15 and 19 Series Service Manual", publisher: "Daikin Comfort Technologies", url: "https://www.daikinac.com/content/assets/DOC/ServiceManuals/SiUS041501E-15-19-Series.pdf", sourceType: "oem-service-manual", scopeNote: "Daikin 15 and 19 Series units documented in service manual SiUS041501E." },
  { id: "lg-general-service", title: "Single-Zone Systems General Service Manual", publisher: "LG Electronics", url: "https://legacy.lghvac.com/resource-service?filename=General_Service_Manual_MFL41161610_All_SZ.pdf", sourceType: "oem-service-manual", scopeNote: "LG single-zone ductless systems covered by general service manual MFL41161610." },
  { id: "midea-aurora-service", title: "Aurora Xtreme Inverter Service Manual", publisher: "Midea", url: "https://www.midea.com/content/dam/midea-aem/col/manuales/minisplit-aurora-xtreme-inverter-seer-19%2C-36000-btu%2C-fr%C3%ADo%2C-220v/Manual%20Minisplit%20Inverter%20ESPA%C3%91OL.pdf", sourceType: "oem-service-manual", scopeNote: "Aurora Xtreme Inverter 36,000 BTU cooling-only 220 V model documented by Midea." },
  { id: "mrcool-code-table", title: "Mini Split Systems Error Codes", publisher: "MRCOOL", url: "https://support.mrcool.com/hc/en-us/articles/39803744782868-Mini-Split-Systems-Error-Codes", sourceType: "oem-support", scopeNote: "MRCOOL generation-specific mini-split code tables." },
  { id: "mrcool-e1-guide", title: "EL01 / E1 Error Code Mini-Split Troubleshooting Guide", publisher: "MRCOOL", url: "https://support.mrcool.com/hc/en-us/articles/28316849365396-EL01-E1-Error-Code-Mini-Split-Troubleshooting-Guide", sourceType: "oem-support", scopeNote: "MRCOOL single-zone and multi-zone ductless systems described in the guide." },
  { id: "mrcool-p1-guide", title: "Troubleshooting P1 or PC-01 Error Code", publisher: "MRCOOL", url: "https://support.mrcool.com/hc/en-us/articles/30875557653908-Troubleshooting-P1-or-PC-01-Error-Code-on-MRCOOL-Mini-Split-Systems", sourceType: "oem-support", scopeNote: "MRCOOL 115 V, 230 V, and multi-zone mini-split families identified in the guide." },
  { id: "mrcool-p0-guide", title: "Troubleshoot P0 / PC00 on a MRCOOL Mini-Split", publisher: "MRCOOL", url: "https://support.mrcool.com/hc/en-us/articles/30946364594068-How-to-Troubleshoot-the-P0-PC00-Error-Code-on-a-MRCOOL-Mini-Split", sourceType: "oem-support", scopeNote: "MRCOOL mini-splits that display P0 or PC00 inverter-module protection." },
  { id: "pioneer-quantum-e1", title: "E1, EL 01, or EL01 Error Codes", publisher: "Pioneer", url: "https://help.pioneerminisplit.com/en-US/e1-error-code-quantum-discontinued-253277", sourceType: "oem-support", scopeNote: "Discontinued Quantum WYS, CYB, RYB, UYB, and FYB series plus listed companion models." },
  { id: "pioneer-current-e1-e2", title: "E1 or E2 Error Codes", publisher: "Pioneer", url: "https://help.pioneerminisplit.com/en-US/e1-e2-error-codes-3334628", sourceType: "oem-support", scopeNote: "Listed Diamante Essenza, Diamante Pro, Quantum Fresh, Hyperformance, and Ultra systems." },
  { id: "senville-eh02", title: "EH 02 Zero-Crossing Signal Detection Error", publisher: "Senville", url: "https://help.senville.com/support/solutions/articles/151000212821-error-code-eh-02-zero-crossing-signal-detection-error", sourceType: "oem-support", scopeNote: "Senville LETO and AURA series models using the applicable AC fan motor design." },
  { id: "senville-leto-codes", title: "Senville LETO Series Error Code Reference Guide", publisher: "Senville", url: "https://help.senville.com/support/solutions/articles/151000211416-senville-leto-series-error-code-reference-guide", sourceType: "oem-support", scopeNote: "Senville LETO series error and protection codes." },
  { id: "fujitsu-rls2-operation", title: "RLS2 Series Operating Manual", publisher: "Fujitsu General", url: "https://www.fujitsugeneral.com/us/resources/pdf/support/downloads/%28OM%29AOU9-12-15RLS2.pdf", sourceType: "oem-operation-manual", scopeNote: "Fujitsu RLS2 9, 12, and 15 class systems documented by the manual." },
  { id: "fujitsu-troubleshooting", title: "AIRSTAGE Mini-Splits Troubleshooting", publisher: "Fujitsu General", url: "https://www.fujitsugeneral.com/us/support/faq/halcyon/troubleshooting.html", sourceType: "oem-support", scopeNote: "General homeowner checks and normal operating behavior for AIRSTAGE mini-splits." },
  { id: "fujitsu-filter-manual", title: "ASUG LZAS Owner's Manual", publisher: "Fujitsu General", url: "https://www.fujitsugeneral.com/us/resources/pdf/support/downloads/%28OM%29ASUG09LZCB.pdf", sourceType: "oem-operation-manual", scopeNote: "ASUG LZAS family cleaning and filter-maintenance instructions." },
  { id: "doe-heat-pump-care", title: "You Installed an Air-Source Heat Pump, Now What?", publisher: "U.S. Department of Energy Building America Solution Center", url: "https://bsesc.energy.gov/sites/default/files/2024-09/CEE_You_Installed_an_ASHP_Now_What_TRC_01.16.24_1.pdf", sourceType: "government-guidance", scopeNote: "Cross-brand air-source heat-pump maintenance guidance for homeowners." },
  { id: "doe-cooling-basics", title: "Energy Saver 101: Home Cooling", publisher: "U.S. Department of Energy", url: "https://www.energy.gov/downloads/energy-saver-101-home-cooling-infographic", sourceType: "government-guidance", scopeNote: "Cross-brand home cooling and basic airflow troubleshooting guidance." },
  { id: "doe-forced-air", title: "Forced Air HVAC Guide", publisher: "U.S. Department of Energy Building America", url: "https://www1.eere.energy.gov/buildings/publications/pdfs/building_america/forced_air_hvac_guide.pdf", sourceType: "government-guidance", scopeNote: "Cross-brand forced-air diagnostic and maintenance principles, including cycling and airflow." },
] satisfies Source[];

